services:
  - type: web
    name: adapt-v3-backend
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: USE_REDIS
        value: true
      - key: QSTASH_TOKEN
        sync: false
      - key: QSTASH_ENDPOINT
        value: https://qstash.upstash.io/v1/publish
      - key: QSTASH_WORKER_URL
        sync: false
      - key: QSTASH_CURRENT_SIGNING_KEY
        sync: false
      - key: QSTASH_NEXT_SIGNING_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_PROJECT_ID
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_BUCKET_NAME
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://adapt-v3.vercel.app,https://adaptord.com,https://www.adaptord.com 